---
# tasks file for ansible-role-redis

- include_vars: "{{ ansible_os_family }}.yml"

- include: install-FreeBSD.yml
  when: ansible_os_family == 'FreeBSD'

- name: Create redis.conf
  template:
    src: redis.conf.j2
    dest: "{{ redis_conf_dir }}/redis.conf"
  notify: Restart redis

- name: Ensure dir exists
  file:
    path: "{{ redis_config_dir }}"
    owner: "{{ redis_user }}"
    group: "{{ redis_group }}"
    mode: 0755
    state: directory
  notify: Restart redis

- name: Ensure log dir exists
  file:
    path: "{{ redis_config_logfile | dirname }}"
    owner: "{{ redis_user }}"
    group: "{{ redis_group }}"
    mode: 0755
    state: directory
  notify: Restart redis

- name: Start redis
  service:
    name: redis
    enabled: yes
    state: started

- include: sentinel.yml
  when: redis_sentinel_enable
