---

- name: Create conf directory
  file:
    path: "{{ redis_conf_dir }}"
    owner: "{{ redis_user }}"
    group: "{{ redis_group }}"
    state: directory

- name: Ensure sentinel.conf exists
  file:
    path: "{{ redis_sentinel_conf_file }}"
    state: touch
  changed_when: false

- name: Ensure sentnel.conf is writable by redis_user
  # as sentinel.conf is modified by redis, it must be owned by the user
  file:
    path: "{{ redis_sentinel_conf_file }}"
    owner: "{{ redis_user }}"
    group: "{{ redis_group }}"
    mode: 0644

- name: See if redis_sentinel_conf_file_ansible exists
  # if the result is true, it means it is the first ansible-play
  stat:
    path: "{{ redis_sentinel_conf_file_ansible }}"
  register: redis_sentinel_conf_file_ansible_stat_result

- name: include redis_sentinel_conf_file_ansible in sentinel.conf
  # make sure sentinel.conf.ansible is included
  lineinfile:
    dest: "{{ redis_sentinel_conf_file }}"
    regexp: "^include "
    line: "include {{ redis_sentinel_conf_file_ansible }}"
    insertafter: EOF
    state: present
  changed_when: false
  notify: Restart sentinel

- name: Create sentinel.conf.ansible
  # this file is static one and all static configuration should go in to it.
  template:
    dest: "{{ redis_sentinel_conf_file_ansible }}"
    src: sentinel.conf.j2
  notify: Restart sentinel

- name: Create rc.conf.d for sentinel
  lineinfile:
    dest: /etc/rc.conf.d/sentinel
    regexp: "^sentinel_config="
    line: "sentinel_config=\"{{ redis_sentinel_conf_file }}\""
    create: yes
    state: present
  notify: Restart sentinel
  when:
    - "{{ ansible_os_family == 'FreeBSD' }}"

- name: Create logdir
  file:
    path: "{{ redis_sentinel_logdir }}"
    owner: "{{ redis_user }}"
    group: "{{ redis_group }}"
    mode: 0755
    state: directory

- name: Start sentinel
  service:
    name: sentinel
    enabled: yes
